name: Deploy node app to production
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source 
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t myagmarsurenmike/mern-front --build-arg REACT_APP_BASE-URL='${{secrets.REACT_APP_SERVER_BASE_URL}}' .
      - name: Publish Docker image
        run: docker push myagmarsurenmike/mern-front:latest    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: docker pull myagmarsurenmike/mern-back:latest
      - name: Delete old Docker container
        run: docker rm -f mern-app-container
      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name mern-front -e MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}' myagmarsurenmike/mern-front

